### ISSUE TITLE
Errors when using "CScope: Find functions calling this function"

### ISSUE THREAD

**Issue by Gruntfuggly** [xulion/scope4code#10]
When I try "CScope: Find functions calling this function" I get some errors:

```
index.js:41 [uncaught exception]: TypeError: Cannot read property 'toString' of null
onError @ index.js:41
(anonymous) @ index.js:110
emitOne @ events.js:96
emit @ events.js:191
window.onerror @ /usr/share/code/resources/electron.asar/renderer/init.js:135
i.globals.onerror @ errorTelemetry.ts:64
index.js:44 TypeError: Cannot read property 'toString' of null
	at CscopeExecutor.execCommand (/home/nscott/.vscode/extensions/xulion.codescope-0.0.4/out/CscopeExecutor.js:62:36)
	at SearchResultProvider.provideTextDocumentContent (/home/nscott/.vscode/extensions/xulion.codescope-0.0.4/out/SearchResultProvider.js:15:40)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:425268
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:92953
	at new n.Class.derive._oncancel (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:72291)
	at Object.t.asWinJsPromise (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:92916)
	at e.$provideTextDocumentContent (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:425232)
	at t.e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:509443)
	at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354786)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354476)
onError @ index.js:44
(anonymous) @ index.js:110
emitOne @ events.js:96
emit @ events.js:191
window.onerror @ /usr/share/code/resources/electron.asar/renderer/init.js:135
i.globals.onerror @ errorTelemetry.ts:64
rpcProtocol.ts:63 Uncaught Error: Cannot read property 'toString' of null
	at CscopeExecutor.execCommand (/home/nscott/.vscode/extensions/xulion.codescope-0.0.4/out/CscopeExecutor.js:62:36)
	at SearchResultProvider.provideTextDocumentContent (/home/nscott/.vscode/extensions/xulion.codescope-0.0.4/out/SearchResultProvider.js:15:40)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:425268
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:92953
	at new n.Class.derive._oncancel (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:72291)
	at Object.t.asWinJsPromise (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:92916)
	at e.$provideTextDocumentContent (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:425232)
	at t.e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:509443)
	at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354786)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354476)
e._receiveOneMessage @ rpcProtocol.ts:63
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
console.ts:123 [Extension Host] WARNING: Promise with no error callback:58
console.ts:123 [Extension Host]% Object {exception: null, error: Object, promise: Object, id: 58}
shell.ts:459 cannot open search:next.find%20?%5B%22All%20functions%20who%20called%3A%22%2C%22next%22%2C3%5D. Detail: Cannot read property 'toString' of null: Error: cannot open search:next.find%20?%5B%22All%20functions%20who%20called%3A%22%2C%22next%22%2C3%5D. Detail: Cannot read property 'toString' of null
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9:2898099
    at Object.v [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9:63281)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9:66555)
    at n.Class.derive._creator._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9:67876)
    at n.Class.derive._creator._chainedError (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9:67235)
    at n (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9:65058)
    at n.Class.define.cancel.then (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9:68685)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9:65127)
    at n.Class.derive._creator._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9:67876)
    at n.Class.derive._creator._setCompleteValue (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9:67570)
e.onUnexpectedError @ shell.ts:459
(anonymous) @ shell.ts:419
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

**Comment by xulion** [comment]
Nigel,

Thanks for using this! I just pushed the first release yesterday I did not thought this will be get used so soon!

May I know the steps you use this? It Did you build the database successfully? Current implementation does not check whethere the database is ready or not (that's my next releases' focus to handle exceptional cases).

**Comment by Gruntfuggly** [comment]
I installed, ran CScope: Build database and then tried stuff out.
The database seemed to build very quickly, which probably means something has not worked?

**Comment by xulion** [comment]
Yeah, does not seems right. Normally it shall take a while as it's basically calls the command line. BTW, do you have cscope commandline work in your environment. I seems forget to mention that to use this extension the cscope must work as a global command.

**Comment by Gruntfuggly** [comment]
That will be what is wrong - I'll install and try again...

**Comment by xulion** [comment]
Yeah, I have to implement the error handling ASAP. Thank you so much!

**Comment by xulion** [comment]
Great to hear! Thanks for the feedback! Next version will add the error handling. More enhancement in near future.

**Comment by xulion** [comment]
fixed in https://github.com/xulion/scope4code/pull/12
