### ISSUE TITLE
Windows: cscope can neither build database nor work with existing one

### ISSUE THREAD

**Issue by guntern** [xulion/scope4code#27]
I tried to use scope4code under Windows with Visual Studio Code Insiders 1.31.0, but I do not get it to work. I downloaded cscope 64bit 15.8a and also tried 32bit, but without any difference.

If I use cscope from the commandline within my project directory it builds a database fine and I can search for symbols as expected. This also shows me, that cscope is correctly in PATH to be accessible.

However, inside of Visual Studio Code it is not working. If I ask to build a database, the status bar shows "building..." for quite a while before switching to "cscope: no database". Of course I then cannot search for symbols. If I use the database built via commandline and copy it in .vscode\cscope\ the status bar shows: cscope: database ready. I then can search for symbols, but no results are shown.

What am I doing wrong? Do I need to configure something in the cscope_conf.json? How are the options in this json file working?

**Comment by xulion** [comment]
I never really tested windows. It's just theory as js supposed to be working on all platforms. I will try test this and see why it's not working. Also I will change this issue as enhancement.

**Comment by piotrwie** [comment]
I found out that 'find' method is used from "gnu" collection, which means there is another unmentioned dependency. Problem is bigger, as the 'find' is a method in system32 folder of windows, which needs to be prepended with patch containing "gnu" find utility (for example from gnuwin32 package).
The "find" is not the single problem. 

Here's some excerpts from my logfiles:
[2019-03-20 09:45:35.707] [renderer1] [info] no standard startup: panel is active
[2019-03-20 09:45:48.086] [renderer1] [error] Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
	at buildDataBase.checkToolSync.then (C:\Users\pwierzc\.vscode\extensions\xulion.codescope-0.0.10\out\CscopeExecutor.js:160:41)
[2019-03-20 09:47:42.746] [renderer1] [error] Cannot read property 'forEach' of null: TypeError: Cannot read property 'forEach' of null
	at provideDefinition.Promise (C:\Users\pwierzc\.vscode\extensions\xulion.codescope-0.0.10\out\DefinitionProvider.js:19:22)
	at new Promise (<anonymous>)
	at DefinitionProvider.provideDefinition (C:\Users\pwierzc\.vscode\extensions\xulion.codescope-0.0.10\out\DefinitionProvider.js:16:16)
	at define.provideDefinition.a.asPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:562:517)
	at t.asPromise.Promise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:58)
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:32)
	at x.provideDefinition (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:562:488)
	at define.$provideDefinition._withAdapter.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:578:89)
	at $._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:502)
	at $provideDefinition (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:578:67)
	at h._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:593:118)
	at h._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:592:777)
	at h._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:591:383)
	at h._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:590:279)
	at define.constructor._protocol.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:588:565)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:43:254)
	at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:39:64)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:43:254)
	at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:168:754)
	at Socket.define.constructor._socketDataListener.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:168:960)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-03-20 09:58:58.018] [renderer1] [error] Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
	at buildDataBase.checkToolSync.then (C:\Users\pwierzc\.vscode\extensions\xulion.codescope-0.0.10\out\CscopeExecutor.js:160:41)
[2019-03-20 10:00:40.593] [renderer1] [error] Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
	at buildDataBase.checkToolSync.then (C:\Users\pwierzc\.vscode\extensions\xulion.codescope-0.0.10\out\CscopeExecutor.js:160:41)
[2019-03-20 10:02:40.236] [renderer1] [error] Cannot read property 'forEach' of null: TypeError: Cannot read property 'forEach' of null
	at provideReferences.Promise (C:\Users\pwierzc\.vscode\extensions\xulion.codescope-0.0.10\out\RefProvider.js:14:22)
	at new Promise (<anonymous>)
	at RefProvider.provideReferences (C:\Users\pwierzc\.vscode\extensions\xulion.codescope-0.0.10\out\RefProvider.js:11:16)
	at define.provideReferences.a.asPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:564:40)
	at t.asPromise.Promise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:58)
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:32)
	at P.provideReferences (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:564:11)
	at define.$provideReferences._withAdapter.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:579:959)
	at $._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:502)
	at $provideReferences (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:579:937)
	at h._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:593:118)
	at h._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:592:777)
	at h._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:591:383)
	at h._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:590:279)
	at define.constructor._protocol.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:588:565)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:43:254)
	at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:39:64)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:43:254)
	at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:168:754)
	at Socket.define.constructor._socketDataListener.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:168:960)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)

**Comment by xulion** [comment]
fix by #37
